const Products = [
  {
    id: 1,
    name: "해피데이 따뜻한 겨울 손난로 대용량 외 7종",
    href: "#",
    mainImageSrc:
      "https://tailwindui.com/plus/img/ecommerce-images/product-page-01-related-product-01.jpg",
    mainImageAlt: "hotpack",
    discountPercent: "30",
    price: "12,600",
    originalPrice: "18,000",
    review: 5,
    reviewCount: "19",
    cardDiscountRate: "5%",
    point: "276P",
    purchaseNum: "8,203",
  },
  {
    id: 2,
    name: "해피데이 따뜻한 겨울 손난로 대용량 외 7종",
    href: "#",
    mainImageSrc:
      "https://trusting-williams-8cacfb.netlify.app/images/hot_focus/hot_focus1.jpg",
    mainImageAlt: "hotpack",
    discountPercent: "30",
    price: "12,600",
    originalPrice: "18,000",
    review: 4,
    reviewCount: "19",
    point: "276P",
    purchaseNum: "8,203",
  },
  {
    id: 3,
    name: "해피데이 따뜻한 겨울 손난로 대용량 외 7종",
    href: "#",
    mainImageSrc:
      "https://tailwindui.com/plus/img/ecommerce-images/product-page-01-related-product-01.jpg",
    mainImageAlt: "hotpack",
    // discountPercent: "30%",
    price: "12,600",
    // originalPrice: "18,000",
    review: 3,
    reviewCount: "19",
    point: "276P",
    purchaseNum: "8,203",
  },
  {
    id: 4,
    name: "해피데이 따뜻한 겨울 손난로 대용량 외 7종",
    href: "#",
    mainImageSrc:
      "https://trusting-williams-8cacfb.netlify.app/images/hot_focus/hot_focus1.jpg",
    mainImageAlt: "hotpack",
    discountPercent: "30",
    price: "12,600",
    originalPrice: "18,000",
    review: 4,
    reviewCount: "19",
    point: "276P",
    purchaseNum: "8,203",
  },
  {
    id: 5,
    name: "해피데이 따뜻한 겨울 손난로 대용량 외 7종",
    href: "#",
    mainImageSrc:
      "https://trusting-williams-8cacfb.netlify.app/images/hot_focus/hot_focus1.jpg",
    mainImageAlt: "hotpack",
    discountPercent: "30",
    price: "12,600",
    originalPrice: "18,000",
    review: 4,
    reviewCount: "19",
    point: "276P",
    purchaseNum: "8,203",
  },
  {
    id: 6,
    name: "해피데이 따뜻한 겨울 손난로 대용량 외 7종",
    href: "#",
    mainImageSrc:
      "https://trusting-williams-8cacfb.netlify.app/images/hot_focus/hot_focus1.jpg",
    mainImageAlt: "hotpack",
    discountPercent: "30",
    price: "12,600",
    originalPrice: "18,000",
    review: 4,
    reviewCount: "19",
    point: "276P",
    purchaseNum: "8,203",
  },
  {
    id: 7,
    name: "해피데이 따뜻한 겨울 손난로 대용량 외 7종",
    href: "#",
    mainImageSrc:
      "https://trusting-williams-8cacfb.netlify.app/images/hot_focus/hot_focus1.jpg",
    mainImageAlt: "hotpack",
    discountPercent: "30",
    price: "12,600",
    originalPrice: "18,000",
    review: 4,
    reviewCount: "19",
    point: "276P",
    purchaseNum: "8,203",
  },
];

export default Products;
