const Products = [
  {
    id: 1,
    name: "쟌슨빌 부대찌개 500g 2+2팩 더진한/오리지널",
    href: "#",
    mainImageSrc:
      "https://cdn.011st.com/11dims/resize/720x360/quality/100/11src/product/2247363143/D.jpg?990000000",
    mainImageAlt: "food",
    discountPercent: "15",
    price: "15,980",
    originalPrice: "21,300",
    review: 5,
    reviewCount: "5,343",
    point: "309P",
    purchaseNum: "8,203",
    coupon: true,
    couponImageSrc: "/assets/coupon.svg",
    couponImageAlt: "coupon",
    couponName: "카카오페이) 마트 쿠폰",
    freeDeliver: true,
    remainProduct: "1,967",
  },
  {
    id: 2,
    name: "해피데이 따뜻한 겨울 손난로 대용량 외 7종",
    href: "#",
    mainImageSrc:
      "https://trusting-williams-8cacfb.netlify.app/images/hot_focus/hot_focus1.jpg",
    mainImageAlt: "hotpack",
    discountPercent: "30",
    price: "12,600",
    originalPrice: "18,000",
    review: 4,
    reviewCount: "19",
    point: "276P",
    purchaseNum: "8,203",
    freeDeliver: true,
    remainProduct: "670",
  },
  {
    id: 3,
    name: "해피데이 따뜻한 겨울 손난로 대용량 외 7종",
    href: "#",
    mainImageSrc:
      "https://tailwindui.com/plus/img/ecommerce-images/product-page-01-related-product-01.jpg",
    mainImageAlt: "hotpack",
    // discountPercent: "30%",
    price: "12,600",
    // originalPrice: "18,000",
    review: 3,
    reviewCount: "19",
    point: "276P",
    purchaseNum: "8,203",
    remainProduct: "670",
  },
  {
    id: 4,
    name: "해피데이 따뜻한 겨울 손난로 대용량 외 7종",
    href: "#",
    mainImageSrc:
      "https://trusting-williams-8cacfb.netlify.app/images/hot_focus/hot_focus1.jpg",
    mainImageAlt: "hotpack",
    discountPercent: "30",
    price: "12,600",
    originalPrice: "18,000",
    review: 4,
    reviewCount: "19",
    point: "276P",
    purchaseNum: "8,203",
    remainProduct: "670",
  },
  {
    id: 5,
    name: "해피데이 따뜻한 겨울 손난로 대용량 외 7종",
    href: "#",
    mainImageSrc:
      "https://trusting-williams-8cacfb.netlify.app/images/hot_focus/hot_focus1.jpg",
    mainImageAlt: "hotpack",
    discountPercent: "30",
    price: "12,600",
    originalPrice: "18,000",
    review: 4,
    reviewCount: "19",
    point: "276P",
    purchaseNum: "8,203",
    remainProduct: "670",
  },
  {
    id: 6,
    name: "해피데이 따뜻한 겨울 손난로 대용량 외 7종",
    href: "#",
    mainImageSrc:
      "https://trusting-williams-8cacfb.netlify.app/images/hot_focus/hot_focus1.jpg",
    mainImageAlt: "hotpack",
    discountPercent: "30",
    price: "12,600",
    originalPrice: "18,000",
    review: 4,
    reviewCount: "19",
    point: "276P",
    purchaseNum: "8,203",
    remainProduct: "670",
  },
  {
    id: 7,
    name: "탑텐 FW인기특가 온에어/ 맨투맨/ 조거팬츠 외",
    href: "#",
    mainImageSrc:
      "https://cdn.011st.com/11dims/resize/720x360/quality/100/11src/product/1815207391/D.jpg?70000000",
    mainImageAlt: "clothes",
    discountPercent: "30",
    price: "12,600",
    originalPrice: "18,000",
    review: 4,
    reviewCount: "19",
    point: "276P",
    purchaseNum: "8,203",
    remainProduct: "670",
  },
  {
    id: 8,
    name: "싱크대거름망 + 커버세트 외 주방베스트",
    href: "#",
    mainImageSrc:
      "https://cdn.011st.com/11dims/resize/720x360/quality/100/11src/product/5298688921/D.jpg?421000000",
    mainImageAlt: "hotpack",
    discountPercent: "30",
    price: "14,140",
    originalPrice: "18,000",
    review: 4,
    reviewCount: "19",
    cardDiscountRate: "5%",
    point: "276P",
    purchaseNum: "8,203",
    coupon: true,
    couponImageSrc: "/assets/coupon.svg",
    couponImageAlt: "coupon",
    couponName: "중복 할인",
    freeDeliver: true,
    deliverDate: "10/24(목) 도착",
    remainProduct: "670",
  },
  {
    id: 9,
    name: "해피데이 따뜻한 겨울 손난로 대용량 외 7종",
    href: "#",
    mainImageSrc:
      "https://trusting-williams-8cacfb.netlify.app/images/hot_focus/hot_focus1.jpg",
    mainImageAlt: "hotpack",
    discountPercent: "30",
    price: "12,600",
    originalPrice: "18,000",
    review: 4,
    reviewCount: "19",
    point: "276P",
    purchaseNum: "8,203",
    coupon: true,
    couponImageSrc: "/assets/coupon.svg",
    couponImageAlt: "coupon",
    couponName: "중복 할인",
    remainProduct: "670",
  },
];

export default Products;
